# Project Configuration
project:
  name: "breast_cancer_classification"
  version: "1.0.0"
  description: "Breast Cancer Classification with MLOps Pipeline"

# Data Configuration
data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  external_data_path: "data/external/"
  
# Model Configuration
model:
  model_path: "models/"
  checkpoint_path: "models/checkpoints/"
  production_path: "models/production/"
  
# Training Configuration
training:
  random_state: 42
  test_size: 0.2
  validation_size: 0.2
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  
# Logging Configuration
logging:
  log_path: "logs/"
  log_level: "INFO"
  
# Feature Configuration
features:
  categorical_columns: []
  numerical_columns: []
  target_column: "Diagnosis"

# Experiment Tracking
experiment:
  name: "breast_cancer_classification"
  tracking_uri: "postgresql://mlops_user:mlops_password@localhost:5432/mlops"
  use_wandb: false
  wandb_project: "breast-cancer-ml"
  use_experiment_tracking: true  # Enable production tracking

# Model Monitoring
monitoring:
  drift_threshold: 0.1
  monitoring_path: "logs/monitoring/"
  alert_email: "admin@example.com"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: true
